vocab/urls.py
from django.conf.urls import url, include
from . import views

terms = [
    url(r'^edit/$', views.EditTermView.as_view(), name='edit_term'),
    url(r'^list/$', views.TermListCreateView.as_view(), name='list_create'),
    url(r'^detail/(?P<pk>[0-9])/$', views.TermDetailView.as_view(), name='detail'),
]

relationships = [
    url(r'^list/$', views.RelationshipListCreateView.as_view(), name='list_create'),
    url(r'^detail/(?P<pk>[0-9])/$', views.RelationshipDetailView.as_view(), name='detail'),
]

urlpatterns = [
    url(r'^$', views.MainPageView.as_view(), name='main_page'),
    url(r'^graph/$', views.VocabGraphView.as_view(), name='vocab_graph'),
    url(r'^terms/', include(terms, namespace='terms')),
    url(r'^relationships/', include(relationships, namespace='relationships')),
]

vocabulary_harmonizer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from common.views import AboutView, MainView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^vocab/', include('vocab.urls', namespace='vocab')),
    url(r'^about/', AboutView.as_view(), name='about'),
    url(r'^$', MainView.as_view(), name='main'),
]

common/models.py
from __future__ import unicode_literals

from django.db import models


class License(models.Model):
    name = models.CharField(max_length=255, unique=True)
    url = models.URLField()

    def __str__(self):
        return self.name


class Organization(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

common/views.py
from rest_framework import generics
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework import status


class MainView(generics.RetrieveAPIView):
    renderer_classes = (TemplateHTMLRenderer, )

    def get(self, request, *args, **kwargs):
        params = {

        }
        return Response(params, template_name='common/main.html',
                        status=status.HTTP_200_OK)


class AboutView(generics.RetrieveAPIView):
    renderer_classes = (TemplateHTMLRenderer, )

    def get(self, request, *args, **kwargs):
        params = {

        }
        return Response(params, template_name='common/about.html',
                        status=status.HTTP_200_OK)

common/templates/common/about.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function() {
            $('#nav-about').parent().addClass('active');
        });
    </script>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col s12">
            <h4>Project</h4>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <p>Some words here about the project.</p>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <h4>Acknowledgments</h4>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <p>Some people who were involved.</p>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <h4>Contact</h4>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <p>Some ways to complain.</p>
        </div>
    </div>
{% endblock %}

common/templates/common/main.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function() {
            $('div.container').removeClass('container');
            $('.card-panel').on('click', function(e) {
                e.preventDefault();
                window.location = $(this).data('link');
            });
        });
    </script>
{% endblock %}
{% block navbar %}
{% endblock %}
{% block content %}
    <div class="row cyan darken-3 z-depth-2">
        <div class="col s12">
            <div class="row">
                <div class="col s12">
                    <h1 class="center-align white-text">VocabularyHarmonizer</h1>
                </div>
            </div>
            <div class="row">
                <p class="center-align white-text">A tool for bridging large and small vocabularies and aligning them for collaboration, development, and research.</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col s4">
            <div class="row">
                <div class="col s10 offset-s1">
                    <a href="//{{ request.get_host }}{% url 'vocab:main_page' %}"><div class="circle deep-orange accent-3 hoverable home-circle"><i class="material-icons black-text true-center" style="font-size: 16rem;">translate</i></div></a>
                </div>
            </div>
            <div class="row">
                <div class="col s12">
                    <div class="row">
                        <div class="col s12">
                            <h5>Domains & Vocabulary</h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s12">
                            <p>View, manage, and edit domains and their vocabularies.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col s4">
            <div class="row">
                <div class="col s10 offset-s1">
                    <a href="//{{ request.get_host }}{% url 'vocab:vocab_graph' %}"><div class="circle deep-purple accent-1 hoverable home-circle"><i class="material-icons black-text true-center" style="font-size: 16rem;">equalizer</i></div></a>
                </div>
            </div>
            <div class="row">
                <div class="col s12">
                    <div class="row">
                        <div class="col s12">
                            <h5>Visualize</h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s12">
                            <p>Visualize the relationships between domains and vocabularies.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col s4">
            <div class="row">
                <div class="col s10 offset-s1">
                    <a href="//{{ request.get_host }}{% url 'about' %}"><div class="circle lime accent-2 hoverable home-circle"><i class="material-icons black-text true-center" style="font-size: 16rem;">chat_bubble_outline</i></div></a>
                </div>
            </div>
            <div class="row">
                <div class="col s12">
                    <div class="row">
                        <div class="col s12">
                            <h5>About</h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s12">
                            <p>Learn more about the project and the people involved.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}